### ISSUE TITLE
[FEATURE] HF Hub

### ISSUE THREAD

**Issue by INF800** [hpcaitech/Titans#41]
### Describe the feature

Any plans to release them (the trained models) on HF Hub?

**Comment by binmakeswell** [comment]
You mean Huggingface Hub?  We are working to provide better compatibility with Huggingface : )

**Comment by binmakeswell** [comment]
Hi @INF800 we post a blog about OPT with Huggingface, you can check it at https://medium.com/@yangyou_berkeley/colossal-ai-seamlessly-accelerates-large-models-at-low-costs-with-hugging-face-4d1a887e500d
